language: node_js
node_js:
  - "8"

sudo: required
services:
  - docker

cache: yarn

script:
  - yarn build

deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

env:
  global:
    - secure: "Bjqd46u1SFinzypxC1ygIFipQp0WO2qwrGK6zk09i00OZvFQcbXmYwHx0ZhMv7g7Br4FiADvkfi6kbSV3DgPQIkuCW8auJwLmI76r1Frw8KuMYqVuV/XLEUGBLjo53Ub9qOHjDEOU877wWFN+QptafmX8w8ZQ8Fl4h/rhBOOqRHFxW1uI5Jt+j5vi7vGxQT3QiFhayMx1nXLJD1eOh33xAt/5U4v9She7G/Mu+U4XGLR3jOynS1CD17+ifqqZSsY3F7X5tsPcUA9bOK1fZOvQTmJEUyl4C8k6xuHoUgCYVPP3kJrkQALlaKqMS6VWvGVQIXb87MXrL1227MGoXMHNRuCnoNfN872lQyQXIeMhBzzXMNvAFx1NvLuAgMswMsAj41/68ywQcWqFg9RqxhyAXHq0PqsF7knD1hmaNO2C0AQFPYtJR012QNZYp9izhRLMUNThhD14SosKdiJiuMUDLIv6PEv7PjcrKyAIF6Hn6w4hCfK/RDUPYOG1xL1+Kv/EOUAG9luR7YO7BQqFu23mALJFL7GV0FnVbvtYitPR6nhTfitJKpYCh8Qot/y6Hxf9VNwqxXFGfPajE86IB2b3LegBeb1ugiK/apRrfrSQ2CEe0lWKvjxLLE4ZVEDXx5HDvEtMR5LGkYlqqtPFMIIqA8JBf2ik7LihXvEz5fdZEk="
    - secure: "FoBLmBYl8jAbXG52Prpyv2Wb0siRxcKRiBGdYPcg+9Kx2bqfnukd747fCfldIOG2wFJsAGacwTkpHe2w+YOBQrkxsw/Na4NP9E0BiUDrpg3s8aXwWb/fb9CwsgRp8qFxHBJVxleMDDoAPgEAET5fUDvnh6h4nq5R/dH9kGzeFPyKXzpTQiVoZaGWmQXJPZDKwZRGcOMaj0E8m5KuD9T6HQdDpGKVaAvXnnmKJ/VGsZzmc8jKEPlbzzwGe7rHAbdpbBeBfPHEE2IOmxmqfxdocWxPBHiW1iuBWiou5BkgBaMCgsueRQZfwW3fqgrSdA82/9ElPYy+DNCNqM0LUlhykA1VifbulmNfK0WEnwc5eNiJcTUMX7Bcip/T9XhN7aOiit1R2oqcS7ca084alumHmeJ/oAd0OA1z1raevlEfYRHXLdsdxotHa1f8rqOGT5aRCO4xC59rfOXpLzybd5DI7NwdIsIakQQr4G6Z72hWK6yu5Sr0HK7An3CZpREw6pLXkt82tVypugqwPHFlH4NvKu0oCey8R3dTOjUdzg1rnDwb+8iSS7YC58TVYDAeHejTdPVhogMbSx2jgLiM6tMME3Xe0IkBpXqA+T/P6Bfad3g3U3KZ1DhcBVsKSZt81eckccWv6BPdezXVBRKm1ONmJVew3C5wddPyGPr+Crvv0sY="
